# Generated by Django 4.2.5 on 2024-09-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='picture_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
