# Generated by Django 4.2.5 on 2024-08-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='info',
            new_name='label_path',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='exhibition',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='style',
        ),
    ]
