# Generated by Django 4.2.5 on 2024-08-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_info_artwork_label_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='folder',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='label_path',
            field=models.CharField(max_length=500),
        ),
    ]
