# Generated by Django 4.2.5 on 2024-08-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_artwork_folder_alter_artwork_label_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='date_of_creation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='folder',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='label_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
