# Generated by Django 4.2.5 on 2024-07-11 05:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('folder', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_of_creation', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('exhibition', models.CharField(max_length=200)),
                ('memo', models.TextField()),
                ('picture', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'db_table': 'artwork_records',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='artworks.folder')),
            ],
        ),
    ]
